name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r backend/requirements.txt pytest
          python -m pip install -r ui/requirements.txt

      - name: Lint
        run: |
          python -m pip install ruff black
          ruff check . --output-format=github
          black --check .

      - name: Run tests
        run: pytest -q
